# Generated by Django 3.2.5 on 2021-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dealID', models.CharField(max_length=255)),
                ('storeID', models.CharField(max_length=5)),
                ('salePrice', models.CharField(max_length=255)),
                ('normalPrice', models.CharField(max_length=255)),
                ('savings', models.CharField(max_length=25)),
                ('steamRatingText', models.CharField(max_length=30)),
                ('releaseDate', models.BigIntegerField()),
                ('dealRating', models.CharField(max_length=5)),
                ('thumb', models.CharField(max_length=255)),
            ],
        ),
    ]
