# Generated by Django 3.2.5 on 2021-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='dealID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dealRating',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='normalPrice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='releaseDate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='salePrice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='savings',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='steamRatingText',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='storeID',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='thumb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
