# Generated by Django 3.2.5 on 2021-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20210729_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='dealRating',
            field=models.FloatField(null=True),
        ),
    ]
